name: Transports
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  transports:
    name: "${{ matrix.transport }}"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        transport: [stdio, sse, streamableHttp]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          # Install project with dev and optional extras similar to unit tests environment
          uv pip install --system .[dev,anthropic,openai,search,e2b]

      - name: Run integration tests for ${{ matrix.transport }} transport
        run: |
          pytest tests/integration/transports/${{ matrix.transport }}
