name: Python Release Drafter

on:
  push:
    branches:
      - main
      - monorepo
    paths:
      - "libraries/python/**"

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "libraries/python/**"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: python-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
